### ISSUE TITLE
Type 1 behavior on bad input

### ISSUE THREAD

**Issue by hannahlawrence** [ahbarnett/finufft#11]
finufft2d1 and finufft3d1 crash Matlab when input sources are outside the expected range [-pi,pi] (finufft1d1 outputs a nonsense answer, but does not cause crash).

**Comment by ahbarnett** [comment]
Thanks for catching that! Yes, the exit() was too aggressive, since it crashes right out through matlab too! Replaced all with return now, so returns to matlab gracefully. I also ensured the chkbnds in spread_opts is set bu finufft, so you should see a warning about which pt is out of bounds come to your screen even when calling from matlab.   Let me know if works for you now.  Cheers, Alex
