### ISSUE TITLE
MATLAB interface to FINUFFT crashes if FFTW is run before FINUFFT

### ISSUE THREAD

**Issue by ahbarnett** [ahbarnett/finufft#17]
Joakim found this one.

Open MATLAB:
fft(1)
finufft1d1(1,1,1,1,1)
causes segfault.

See known issues for workaround.

This was not fixed by correctly pairing malloc/free rather than fftw_free - Alex 2/14/18

**Comment by janden** [comment]
This seems to be a separate issue from that caused by `fftw_free`. You can reproduce it with other functions as well, like
```
conv2(randn([32 1]), [1 1 1]');
finufft1d1(1,1,1,1,1);
```
Interestingly, you can get things to work again by calling `fft` on a big array
```
fft(1);
fft(randn(800, 1));
finufft1d1(1,1,1,1,1);
```
This doesn't crash. MATLAB seems to treat small FFTs and big FFTs differently in terms of the libraries it calls.

In these segfaults, MATLAB always crashes at the first call to FFTW in the MEX file (usually `fftw_init_threads` or `fftw_alloc_complex`). So it looks like it's some issue with the linking.
